#server:
#  port: 8771

#\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-server
  #指定从哪个配置中心读取
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      profile: test

# 使用跳板机访问远程数据库
  datasource:
    url: jdbc:mysql://localhost:13306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zly
    password: zly_1988
    type: com.alibaba.druid.pool.DruidDataSource
#  datasource:
#    url: jdbc:mysql://rm-wz9ol46kro5h2gbjqzo.mysql.rds.aliyuncs.com:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: zly
#    password: zly_1988
#    type: com.alibaba.druid.pool.DruidDataSource

#  rabbitmq:
#    host: 8.129.176.18
#    port: 5672
#    username: guest
#    password: guest

#暴露全部的监控信息
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#rocketmq.producer
rocketmq:
  producer:
    isOnOff: true
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    maxMessageSize: 4096
    sendMsgTimeOut: 3000
    retryTimesWhenSendFailed: 2
