server:
  port: 8781

#\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

#自定义负载均衡策略
#product-server:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#配置feign超时时间,如果不配置,则会优先使用hystix的默认时间(1s),而不是feign的默认超时时间(6s)
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000
  hystrix:
    enabled: true

#设置hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#暴露所有的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
